### ISSUE TITLE
Error: Class 'Drupal\commerce_shipstation\ShipStationSimpleXMLElement' not found

### ISSUE THREAD

**Issue by chris-archer-whisky** [trigdog/commerce_shipstation#6]
I have installed the module and set up the store using the guide https://help.shipstation.com/hc/en-us/articles/360025856192-Custom-Store-Development-Guide But I am getting the following messages

But I am having issues authenticating the custom store in shipstation

**Comment by chris-archer-whisky** [comment]
I do see this 

`
Path: /shipstation/api-endpoint?SS-Password=3hK23oBhs4f6qdrMawRk&SS-UserName=dd-shipstation. Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: WWW-Authenticate: Basic realm ="ShipStation XML API for Drupal Commerce in Drupal\commerce_shipstation\ShipStation->endpointAuthenticate() (line 102 of /app/web/modules/contrib/commerce_shipstation/src/ShipStation.php).
`

**Comment by chris-archer-whisky** [comment]
This seems to be the issue 

`Error: Class 'Drupal\commerce_shipstation\ShipStationSimpleXMLElement' not found in Drupal\commerce_shipstation\ShipStation->exportOrders() (line 164 of /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/sites/decadent.canvas-space.com/modules/commerce_shipstation/src/ShipStation.php)
#0 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/sites/decadent.canvas-space.com/modules/commerce_shipstation/src/Controller/ShipStationEndpointController.php(93): Drupal\commerce_shipstation\ShipStation->exportOrders(Object(DateTime), Object(DateTime), 0)
#1 [internal function]: Drupal\commerce_shipstation\Controller\ShipStationEndpointController->shipstationEndpointRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#3 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#4 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#5 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#6 /data/disk/o6451218963/static/canvas_v1.15.0_dev/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /data/disk/o6451218963/static/canvas_v1.15.0_dev/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /data/disk/o6451218963/static/canvas_v1.15.0_dev/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /data/disk/o6451218963/static/canvas_v1.15.0_dev/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#18 {main}
.`

**Comment by trigdog** [comment]
I started this port from D7 to D8 to just get the ball rolling.  Never even tried connecting.  I never heard from the maintainer of the module (https://www.drupal.org/project/commerce_shipstation) and ended up going in another direction.  I will not be doing any more on this unfortunately.

**Comment by chris-archer-whisky** [comment]
Can I ask what solution you went for in the end?
